### ISSUE TITLE
Pinned direct message chats don't stay pinned in Signal Desktop while Molly is online

### ISSUE THREAD

**Issue by Anvil5465** [mollyim/mollyim-android#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

See https://github.com/signalapp/Signal-Desktop/issues/6743

If my phone is connected to the internet while attempting to pin a direct message chat in Signal Desktop, the chat will wait a few seconds before unpinning itself. If I disconnect my phone or computer from the internet, it stays pinned. Because the other user who reported this problem is also using Molly, I think it may have something to do with how the new version of Signal Desktop is interacting with the current version of Molly.

### Steps to reproduce

1. Connect both desktop and phone apps to the internet
2. Attempt to pin chat on desktop

### Molly version

v6.41.3-2-FOSS

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 6a

### Link to debug log

https://debuglogs.org/android/6.41.3/76e8e94690d6630f5742c48860a08cd8e122444f45c9d0899ec2e645b27b67e4

**Comment by jm355** [comment]
I tried unlinking and deleting all data on my linked device, then re-linking. That didn't fix it. One interesting thing that I noticed both before and after trying that, the contact in question hasn't set a profile pic and I haven't either, so it's just the colorful initials default. On my phone it's a light pink, on my linked device it's gray. Maybe the two devices aren't recognizing that it's the same person somehow?

**Comment by taivlam** [comment]
@jm355 Colored letter avatars  (for Signal users using default profile avatars) don't correspond between the phone by default.  I'm using both Signal Desktop (stable production) and Signal Desktop Beta on the same laptop, and Signal users with default avatars have different avatar colors.

**Comment by taivlam** [comment]
@Anvil5465 @jm355 BTW, do you mean you have *no* secondary Molly clients as linked devices?  Just making sure that this issue isn't a duplicate of #266.

**Comment by jm355** [comment]
I only have 2 devices: my phone with molly foss, and my laptop with signal-desktop linked to my phone

**Comment by Anvil5465** [comment]
I also have no secondary Molly clients

**Comment by jm355** [comment]
One interesting thing that happened, I unpinned the chat on my phone, then pinned it on desktop and then pinned it on my phone (the same chat), and I got a toast notification saying only 4 chats can be pinned at a time. So somewhere along the way signal desktop and molly foss are not recognizing that the chat is the same

**Comment by taivlam** [comment]
Ok, that makes things clearer - this issue is different than the one I am facing.  IIRC, Signal Desktop used to keep the order of pinned chats correct (b/f I added a secondary Molly device).

**Comment by snakedoctr** [comment]
Any update on this?  

I'm having this same issue.  I have Molly on my phone, and signal-desktop on my desktop.  If I pin a chat on my desktop, within a few seconds it's unpinned.  If I pin a chat on Molly, it stays pinned, but does not get pinned automatically on my desktop.

**Comment by albirs** [comment]
i have the same issue (Molly UP, Signal Desktop Mac, Signal Desktop PC) **but only with the "note to self"-Chat**. 
Other Chats keeps pinned correct in all APPs ...

**Comment by Anvil5465** [comment]
> Other Chats keeps pinned correct in all APPs ...

Are the other chats group chats? Group chats stay pinned for me, but direct messages do not.

**Comment by snakedoctr** [comment]
I tested group chats as well, and like @Anvil5465, grouped chats stay pinned on both Molly and Signal desktop for me.

**Comment by albirs** [comment]
> > Other Chats keeps pinned correct in all APPs ...
> 
> @albirs Are the other chats group chats? Group chats stay pinned for me, but direct messages do not.

your right... 
never tested this way - although its described in the topic. (🙈) 
so group chats seems work to pin, direct messages not including "note to self"

**Comment by kNsja5w** [comment]
This also happens to my pinned chats on macOS with Molly as client on Android. 

1. Group chats stay pinned
2. Note to Self and Direct Messages become unpinned...

...when opening/using Molly on Android.

**Comment by albirs** [comment]
... seems fixed in v6.47.4-1 (using v6.47.4-1.up1)  
... at least in my Windows Desktop Singal app doesn't  happend anymore

**Comment by snakedoctr** [comment]
For my after the upgrade to v6.47.4-1 (using Github APK) it's slightly better.  If I pin from Molly, Signal on my desktop does not reflect the change.  If I then unpin everything from Molly, and pin from my desktop (direct messages and note to self), that gets reflected back on Molly.  But then later it gets unpinned -- I'm still seeing under what conditions that happens.

**Comment by Anvil5465** [comment]
Actually, it seems like mine will stay pinned for a while, but like @snakedoctr says, they eventually get un-pinned on desktop. Also not sure what exactly is triggering the un-pinning.

**Comment by snakedoctr** [comment]
It's still happening for me, too, @Anvil5465.  Still not sure what makes them unpin themselves.

**Comment by albirs** [comment]
... i had to have re-pinned once, on ALL desktop (Mac and Win) apps, when the update came out
since this all chats stay pinned...

**Comment by neunzehnachtneun** [comment]
Seems solved to me too. I am using molly-foss 7.0.2-1 and signal desktop 7.2.0-beta.1.
At least I can pin chats on desktop, the pinned chats are transferred to molly and stay pinned.

**Comment by johanw666** [comment]
Nope, not fixed. As soon as I pin a new chat in the linked Molly all pinned chats disappear on the main device. Re-linking does not work anymore. I originally had the problem with pinned chats of unregistered accounts but now it also happens with registered accounts.

**Comment by derei** [comment]
Confirmed: I used two android devices: primary a phone, secondary a tablet. And regardless on which device I would pin a message, it would unpin. Is like the other device is always overwriting the pinned state. I even tried to pin the same chat in both devices, but it didn't persist.

**Comment by taivlam** [comment]
### Today

When I added a new Signal Desktop device today, I experienced this issue again.  I thought this issue disappeared after Molly reached version 7.x.x (i.e., usernames available on stable production Signal), but this was not the case.  Here are the debug logs for the devices used today:

* Pixel 5a [debug log](https://debuglogs.org/android/7.1.3/e486c75780b682f373435fcb62f8e10419d47e80c74f4677c77531ac1b991798)
* Signal Desktop [debug log](https://debuglogs.org/desktop/7.4.0/1037047676615b0eaa8d695aa53eff30f11fa57c64970ec55aadaf655ba142bb.gz)

### Yesterday

Also, I experienced this issue yesterday, after unlocking Molly on my secondary Molly device after a while of being locked:

* Pixel 5a [debug log](https://debuglogs.org/android/7.1.3/4b23ab164364fa7c607bfd8c0c3663af4145a522146135ff05aa1a83d5f6c4a8)
* Pixel Tablet [debug log](https://debuglogs.org/android/7.1.3/27449ccdb50ef11eca2affce41855ac73be0116c0c10a400dc63cc4c21e2120c)
