### ISSUE TITLE
Add option to disable new color palette

### ISSUE THREAD

**Issue by underdog-1** [mollyim/mollyim-android#447]
### Guidelines

- [x] Yes, I have searched the existing requests

### Feature Description

Hi, thanks for the great project. I use it along with Mollysocket which is a great combination. :) 

I just updated Molly and I don't necessarily like the new color palette. It would be much preferred if there was an option in the appearance menu to change back to the old theme.

**Comment by CompeyDev** [comment]
Me too! I would very much prefer a Material You toggle, which was one of the main reasons I preferred Molly's UI design more than the official Signal app.

**Comment by CompeyDev** [comment]
I thought this was already implemented in a previous release? I remember a little while ago, the passphrase screen and the menu items started using my accent color. 

Perhaps it was Molly's own color which coincidentally happened to be similar to my configured accent color.

**Comment by TXort** [comment]
Here after updating the app.

The blue color is giving me a headache. I hope neutral grey returns in the future. Will probably switch to Signal You until then.

On a side note, it seems everyone for some reason is switching to blue colors for dark mode instead of neutral grey (Libadwaita on Linux). I don't really get the reason why.

**Comment by cyrneko** [comment]
Libadwaita *does* use a neutral grey background with a blue accent... 🤔

**Comment by valldrac** [comment]
You can change the chat background to neutral gray in settings.

Also, if you choose a solid color image as wallpaper, chat bubbles and some buttons will turn gray.

**Comment by TXort** [comment]
> Libadwaita _does_ use a neutral grey background with a blue accent... 🤔

I edited the comment to explain that part better.

Anyway, I do like the new icons too. The dark blue theme is pretty, but it's not for me, as I explained.

**Comment by inferenceus** [comment]
I updated Molly less than 5 minutes ago and already have a headache along with being able to not process what I'm seeing properly due to sensory vision issues.

I changed the wallpaper to a solid colour, but the overall UI did not change or revert to the previous style. This would be best implemented as a toggle or general colour scheme in the app. My eyes are literally struggling to read anything in the app since this update.

**Comment by inferenceus** [comment]
Does Molly even obey the system Material You configuration? It seems to be hard-coded from my testing.

On GrapheneOS, I have the greyscale option set, which every Material You-based app on my phone obeys, other than Molly. No matter which system colour scheme I select, Molly remains unchanged.

**Comment by inferenceus** [comment]
> As a user I feel like for colors, its best not to diverge too much from signal's implementation.
> 
> I believe the decision for the blue tones was to give the app more molly-like feel.

Apps should not force a specific colour scheme, especially when using Material You which had colour options. It is an accessibility nightmare when apps do this and don't obey the user's configuration.

It is due to disability reasons why I cannot tolerate the Molly colours since this version, and I have even had to hand off management of my groups to another Admin temporarily while I wait to see if this issue is resolved, because I cannot use the app now for more than 5 minutes without becoming physically nauseous.

The worst part of this is Molly is the only app on my device which fails to change its colour scheme based on my system Material You configuration, which is explicitly greyscale for a accessibility reasons.

**Comment by inferenceus** [comment]
> What are the Molly devs thinking? The new theme is an eye sore and then they go to provide no alternative. Sad as I really enjoyed this fork.

I cannot agree more.

Unfortunately, despite the security advantages and better design of Molly over Signal, I will be forced to switch (downgrade, in my book) to Signal if this issue is not resolved promptly. It was a terrible, anti-accessibility decision and it is a bug, not a feature, as far as I am concerned.

**Comment by inferenceus** [comment]
> Guys, calm down. Molly is still a great app providing better push support to say the least. Devs are doing it for free in their free time. We can only request and hope they change it in coming versions.

@jayb-g There is a *huge* difference between making a demand in open-source software to completely destroying usability for users, especially in the aspect of ignoring and not putting thought into disabled users who *require* accessibility.

What made the Molly developers believe forcing this low-contrast, trippy colour scheme onto every user as if they are the same as them, despite Material You having some sort of API which allows users to decide what's best for their needs, was a good idea?

With all due respect, and I have a *lot* of it for the Molly developers for creating such an outstanding fork of Signal (Molly is what Signal should have been, if you ask me), I absolutely cannot stand by without stating my case. The app becoming unusable has further-reaching consequences than just the app; I now cannot respond to people in my own groups, and cannot moderate them.

If the Molly developers disagree, and they are free to, I will simply switch to Signal, and perhaps fork Molly in the future. They aren't required to fix this accessibility-breaking bug, but it's not going to go down well with disabled people requiring it to be fixed if they don't.

**Comment by CompeyDev** [comment]
> The blue color is giving me a headache. I hope neutral grey returns in the future. Will probably switch to Signal You until then.

The contrast seems to be a lot less stark / stinging on light mode, you might have some luck trying that in the meanwhile until this gets addressed. Can't believe I would ever recommend light mode to someone, lol.

CC @TXort @grapheneloverdev

**Comment by alizair** [comment]
Yes please I also vouch for having an option to enable / disable the new purple accent in the app.

**Comment by splattergamesextended** [comment]
You can add me to the list of people disliking this new Joker theme. I had to turn on light mode to escape this weird color scheme - the only app out of 100 in light mode now. I much prefer Material You whenever possible.

**Comment by vmkxyz** [comment]
adding my vote to revert back to the older theme

also I don't see a reason to remove the old app icons entirely, they could have just stayed there alongside the new ones

**Comment by kdkopx** [comment]
Hi, long time Signal & Molly user here, I really appriciate the project and the devs for putting all the hard work in, but I'm +1 for at least having the original theme as an option in the menu.

**Comment by SyCoREAPER** [comment]
> It's absolutely disgusting and am glad so many others don't like it either. The dark purple isn't working for me.
> 
> I could/can accept dark not being AMOLED (though I wish there was an AMOLED theme), purple isn't appealing 

Lwt me emphasize however that while that was very blunt and to the point, I appreciate the work the developers have put in. It's not a demand, that's not how FOSS works (or should it with other apps) but rather a hopeful statement.

**Comment by valldrac** [comment]
To keep the discussion balanced, I want to highlight that we've received a lot of positive feedback about the new theme across social media, email, DMs, and more.                                                                                                 

We understand that design is subjective, and not everyone will like the changes. There's no right or wrong here. Our new theme is intentionally opinionated and may take time to get used to. However, since the vast majority of users love it and have celebrated the change, we'll keep it.                        

If you find the new design challenging to use for functional reasons rather than aesthetics, we'd love to hear specific usability feedback, though we intend to maintain the overall design. At Molly, we're open to constructive suggestions. We know that some users prefer the old theme, but since maintaining it is costly, we won't be bringing it back. We're exploring adding Material You dynamic colors as an alternative option. However, this would require significant development work. We may even open a bounty to find developers to help implement it. We're talking about supporting both the current theme and Material You, rather than replacing the current theme.
 
If you have specific suggestions, like tweaking color saturation, adjusting UI elements, or modifying the chat settings color behavior, please open a feature request with screenshots and details. We'll carefully review each one. However, we'll maintain key elements of our design identity, such as the purple color.

**Comment by minosimo** [comment]
In a low light environment, the dark purple feels fluorescent and quite objectivrly and literally hurts to look at, same as a blacklight.

**Comment by inferenceus** [comment]
@valldrac 

> Our new theme is intentionally opinionated and may take time to get used to.

So, what you've essentially done is completely disregard people who have functionality needs just to suit your unimportant form. Every person with visual impairment(s) reading this now know this was a conscious choice to throw them all under the bus. You prefer trying to be cool and smart by changing to a design which is, as stated yourself, "intentionally opinionated" with the assumption that everyone can just "get used to it". This is anti-accessibility *by design*.

> If you find the new design challenging to use for functional reasons rather than aesthetics, we'd love to hear specific usability feedback, though we intend to maintain the overall design.

You say this as if harming disabled people is completely fine because you'll just "fix it later"; how about you ask for feedback *before* you destroy the usability?

As for *my* feedback, see my previous comments in this issue.

> We know that some users prefer the old theme, but since maintaining it is costly, we won't be bringing it back. We're exploring adding Material You dynamic colors as an alternative option. However, this would require significant development work.

You say this as if it isn't going to take *us* considerable amounts of time to create backups and migrate to another compatible app, such as Signal, as well as the stress this is going to cause. Again, no thought put into this decision, simply because you thought it looked cool.

> If you have specific suggestions, like tweaking color saturation, adjusting UI elements, or modifying the chat settings color behavior, please open a feature request with screenshots and details. We'll carefully review each one. However, we'll maintain key elements of our design identity, such as the purple color.

You'll take feature requests to change pretty much everything other than what needs to be changed? Had you read the comments in this issue, you would see that the biggest complaint *is* the purple colour. It doesn't seem to me as if you're willing to change anything; you've already come to a decision to stick with this design.


As a long-term user of Molly and a member of the security and privacy communities, the decisions made by Molly management have been harmful, simply due to the fact that you have now, explicitly, pushed many people away from your security-and-privacy project. Take note when I say that *you* are the one who has forced me to downgrade my own security and privacy due to disastrous decisions *you* have made. In the end, if we can't use the app, we can't use the security and privacy features, either. I can no longer recommend Molly as a Signal client due to this reckless decisions made by the Molly team; this is a direct consequence of this event; trust has been lost.

**Comment by SyCoREAPER** [comment]
Honestly I'm not seeing where the difficulty would lie with the theme. You find the Hex value for the purple you or upstream implemented and replace it with a less offensive color hex value.

As stated rather not so delicately by @inferenceus , you are missing the point that the purple is the issue. It's trivial to change with minimal development resources needed outside of 'find and replace'.

Since there is no making everyone happy, simply revert it back and work on a theme engine in app that has a color wheel or just a hex value field for individual app elements.

Change isn't the issue, it's unpopular and undesirable change that is. The feedback has it that the purple is both unpopular and an issue for many from an accessibility standpoint.

**Comment by SyCoREAPER** [comment]
> And even in csse it does take up more development resources to maintain a theme, isn't it better to just rely on Signal for the theme implementation? Why change it at all? 
> 
> As a workaround, as @valldrac suggested, I have temporarily changed wallpaper to solid grey-ish color, which somewhat makes it bearable. But it doesn't fix the issue. Hopefully molly devs will take some action to fix it in coming version.

Ive done the same and really should have suggested this but didn't think it would be as impactful.

Unfortunately my eyes nearly burned out their sockets when I pushed the emoji for the app instead of keyboard and my black background suddenly had UV light popup eliminate my retinas.

Again, respect to the devs for what they do but I'd really like to see this positive feedback claimed above. It read more like PR statement from Ubisoft and EA blowing smoke up our collective hiney-holes though rather than actual feedback.

If the devs really want feedback, in-app pop-up that directs to a simple Google Web form "Do you like the new dark theme?" 'Yes' / 'No'
Work from there. I'm out out. Not going to feed this thread further though. I've said my piece and the sentiment appears to be shared.

I hope the Molly Team will reconsider their decision as well as the communities feedback.

**Comment by splattergamesextended** [comment]
> may take time to get used to.

Oh it will take time to get used to forking Molly with a *human aesthetic*. This is just one more of these examples in FOSS where the devs feel the need to introduce some quirky change that reflects their personality into a product used by everyday people who just wish to have a neutral look. And this is actually worse than all those 90's looking apps where no one has a clue about design and made the whole layout in MS Paint. 

>There's no right or wrong here

True, but there is popular and unpopular. And these are much less subjective because the numbers win.

So, what have we learned today? That FOSS will always stay the same and follow the trend of GNU/Linux with a billion forks of pretty much the same thing because the devs always feel like "thinking different" is a great idea. I don't know why it is so hard to just have a black/white theme like literally every other app out there - or at least follow Material You standards. I'm pretty upset that I have to waste time now, keeping a fork up to date which could have been completely avoidable.

**Comment by valldrac** [comment]
> I would very much prefer a Material You toggle, which was one of the main reasons I preferred Molly's UI design more than the official Signal app.        

We're going to experiment with Material You as a second alternative to the current light/dark theme. Users who have customized a palette on Android will be able to apply to Molly as well. Since Signal doesn't support Material You, we'll have to implement it from scratch.

> Here after updating the app. The blue color is giving me a headache. I hope neutral grey returns in the future. Will probably switch to Signal You until then." 

Probably we'll use [Signal You](https://github.com/nekorubu/Signal-You) color palette as a reference for our Material You implementation. So if you help them to improve theirs, we'll be able to take advantage of it too.  

> But it doesn't change the app color theme. Basically all greys are replaced with blue including in-chat colors.                                       

We can't change the entire app based on chat color settings, as implementing dynamic color changes requires extra code for each screen and component. That said, we'll try to at least refine the most noticeable elements, like reactions overlays, and pop-up menus in the chat screen. 

> In a low light environment, the dark purple feels fluorescent and quite objectively and literally hurts to look at, same as a blacklight.

Got it. We'll review the dark purple in low-light settings and consider adjustments to improve readability and comfort.

**Comment by ex-alice** [comment]
**Old dark theme was just perfect**, even better than potential Material You implementation which sucks because of general contrast, also because it's more _custom pallette color_ like, not fully dark/black like old theme and no matter which color palette you choose it still doesn't get to look as good as old dark theme. 

Dear devs, please **restore old theme** or at least **add an option to change it back**. As you can see **old dark theme is liked by community a lot** so why change/experiment with new purple theme or Material You implementation.

**Comment by s38b35M5** [comment]
Thanks for all the great comments here. I'm so very glad I always check release notes and that I dug through the assets and issues to are the changes and the reaction to them. I'm not going back to Google-ified Signal; I'll stay on the previous version until there is a solution to the low contrast, retina-burning colors I see in the screenshots from @grapheneloverdev. 

Seems a shame to drop a change like this with no user input from the community beforehand. According to the [International Agency for the Preventing of Blindness](https://www.iapb.org/learn/vision-atlas/magnitude-and-projections/global/), over 1 Billion people have some form of vision impairment. Seems a lot of people to forget might have issues with your unprompted rebranding...

**Comment by valldrac** [comment]
We've analyzed the luminance differences between the old and new color palettes across both the light and dark themes, testing the main screen and chat screen. Here's what we found:

- Light theme: Approximately 1.6% darker than before, resulting in a slight reduction in brightness. This minor change may help reduce glare and improve readability.
- Dark theme: 23% darker on the main screen and 28% darker in chat. In theory, this should ease eye strain in low-light conditions.

However, many of you have reported increased eye strain, headaches, and a harsh fluorescent glow, despite the overall darker design. We originally assumed a darker theme would be more comfortable, but a few factors may have contributed to the opposite effect:

- Pixel Blooming: On some displays, bright colors can appear to glow or halo effect against a nearly black background.
- PWM Dimming sensitivity: Many OLED displays use PWM for brightness control, which always introduces flicker, but it becomes most noticeable at lower brightness levels. Some people are more sensitive to this flicker, leading to headaches and eye strain.
- Perceived brightness: Higher contrast can make bright elements feel more intense, and could cause visual fatigue for some users as their eyes adjust between dark and bright areas.

We didn't fully consider the device screen technology. Different smartphones render dark theme differently, affecting comfort. The current design may work well on some screens but feel uncomfortable on others.

We're testing these changes:

- Slightly increase background luminance to soften contrast.
- Tone down purple colors to make them less intense.

To better understand how different displays handle the new theme, it would be helpful to know your device model or, even better, its screen technology.

Thanks to everyone who has shared their experiences so far.

**Comment by s38b35M5** [comment]
Pixel 5 90Hz OLED, Boosted color mode, LOS. 

I haven't upgraded yet, but I've never seen my screen flicker, and I've owned six OLED phones. One other thing of note: the old (current to me) color theme with grey on darker grey is already low contrast, and the users above mention preferring it. I dont want to assume they have no problem with low contrast, as they did mention contrast as a concern, but I'm sure they'd be happy to help test colors so you dont have to keep making decisions in a vacuum.

**Comment by valldrac** [comment]
You can try going to Android settings, then Display > Colors, and selecting "Natural".

I’m not saying this is the solution, but at least it will give you a better idea of what we intended with the new theme, closer to the design you had created.

**Comment by inferenceus** [comment]
@valldrac 

> We're going to experiment with Material You as a second, optional alternative to the current light/dark theme. Users who have customized a palette on Android will be able to apply to Molly as well. Since Signal doesn't support Material You, we'll have to implement it from scratch.

This is the *only* way you're going to make Molly acessibility-friendly; period. Your own opinion and ideology do not change reality and what people actually *need* to use to be able to see and use the app.

> Got it. We'll review the dark purple in low-light settings and consider adjustments to improve readability and comfort.

The main issue is the ***purple***. I'm unsure what the obstacle is to you understanding that. As I stated in my previous comment, you seemingly aren't willing to change the part which actually needs to be changed.

> Tone down purple colors to make them less intense.

Again, ***hellbent*** on keeping the purple when that's literally the entire issue, at least on my end. I've already encountered multiple people with vision impairment(s) due to hypersensitivity, etc, and they are now unable to use Molly. With the increasing amount of autistic-and-similar people part of the population, you are making your app, and its security and privacy, inaccessible and completely unusable by more people as time passes. **Drop the forced purple**.

> To better understand how different displays handle the new theme, it would be helpful to know your device model or any relevant details, such as screen technology, OS version, or custom display settings on Android.

Not that it matters to me at this point, my device specifications in regards to this issue:
**Device:** Google Pixel 8 Pro
**Display technology:** OLED
**Operating system:** GrapheneOS (Android 15 QPR2)

On top of those things, I use a *greyscale* Material You configuration so I can actually see and use apps, something your newly-introduced purple will never provide.

**Comment by inferenceus** [comment]
@valldrac 

> You can try going to Android settings, then Display > Colors, and selecting "Natural".

My device is already using this configuration. I hate to imagine what it would be like set to a vivid mode.

**Comment by Snuupy** [comment]
What a jarring change. I did not expect that when I upgraded the app without reading the release notes.

device: pixel 9
display: oled 120hz
OS: A16 QPR2

**Comment by valldrac** [comment]
To complete the implementation of Material You integration (#463) we need your support. We'll be sharing officially signed APKs with the new theme for testing. If you're interested, please join our Matrix room at [#mollyim-testing:matrix.org](https://matrix.to/#/#mollyim-testing:matrix.org) to help test, report bugs, and provide feedback.

We're especially focused on:

- Accessibility issues (e.g., contrast, readability).
- Suggestions to refine the dynamic theme.
- Color inconsistencies or any bugs with the new settings.

We understand the discussion has been heated, but please keep in mind that our resources are limited. Without your help in testing and providing feedback, we won't be able to complete and merge this feature.

**Comment by neunzehnachtneun** [comment]
Just for the record: Android has introduced a neat working color correction with different modes which could be helpful for a lot of people.

**Comment by Priveetee** [comment]
@DeadSecTr I think this is a beautiful color but yeah maybe just do something simple, either back to the original version or the material color :)

**Comment by valldrac** [comment]
Just a quick update: the Material You integration is now complete and merged! Huge thanks to everyone who tested it, report issues, and share feedback.

**Comment by s38b35M5** [comment]
Does anyone have screenshots to show the improved look? I've been holding off updating for this reason.

**Comment by cyrneko** [comment]
> Just a quick update: the Material You integration is now complete and merged! Huge thanks to everyone who tested it, report issues, and share feedback.

Does this include dynamic bubble colors? i.e having the bubbles (by default) use a MD3 Monet color instead of the default purple?

**Comment by CompeyDev** [comment]
> > Just a quick update: the Material You integration is now complete and merged! Huge thanks to everyone who tested it, report issues, and share feedback.
> 
> Does this include dynamic bubble colors? i.e having the bubbles (by default) use a MD3 Monet color instead of the default purple?

No, this does not.

**Comment by s38b35M5** [comment]
@grapheneloverdev or @underdog-1 have you tried this recent release to confirm the problem is fixed from your perspective? I'm reluctant to update since the change to purple.

**Comment by s38b35M5** [comment]
> > [@grapheneloverdev](https://github.com/grapheneloverdev) or [@underdog-1](https://github.com/underdog-1) have you tried this recent release to confirm the problem is fixed from your perspective? I'm reluctant to update since the change to purple.
> 
> Yes, it works great. Simply update the app, and turn on the dynamic colors option in the settings.

For the record, the purple is gone, and those who want to continue the status quo can do so?

**Comment by Hasshu** [comment]
> Material You integration is now complete and merged!

That's cool and all, but what about the purple flashbang on startup?

**Comment by s38b35M5** [comment]
Very pleased that we can disable the new color palette. 

Still a shame that the new palette is so garish... I'd give it a try over material you, but the weird purple chat bubbles are like black light, drilling into my eyes, made more obvious by the darker background. Why was the new purple chosen over the old one? The old purple seems so much easier on the eyes... 

Oh well... devs can get bored and add extra code to their apps for no real purpose whenever they like, but Spaghetti God forbid we get extra code to allow the old preferred behavior of applying color to your contacts' chat bubbles instead of your own (cuz who doesn't need to see their own chats in a certain color so you know when _you're_ talking...?) that was taken away upstream.

Thx again for this feature.
