### ISSUE TITLE
Suggestion: Is it possible to merge Molly-FOSS and Signal-JW ?

### ISSUE THREAD

**Issue by natur960** [mollyim/mollyim-android#71]
Suggestion: Is it possible to merge molly-foss and Signal-JW ?

both forks got advantages over signal - then is it possible to combine the two ? 

@valldrac  @johanw666   - what do you guys say ? :)

https://github.com/johanw666/Signal-Android/releases
https://github.com/mollyim/mollyim-android

**Comment by johanw666** [comment]
Yes, that's possible. I run such a version myself when I test Molly. I have already discussed this, and Molly has already taken over my code to show different map types of Google maps (in the non-foss versions) but @valldrac  didn't want to take over my "controversial" options like ignoring remote delete and view once.

Anyway, if you want such a version I have the code I use here: https://github.com/johanw666/mollyim-android/tree/5.23.8-1.0-JW

**Comment by valldrac** [comment]
It's true. I don't want to add the features of ignoring remote delete and view-once. Also, another "controversial" feature for Molly security is Johan's plain-text backups.

If there is any other feature you would like to add to Molly from Signal-JW we can discuss it.

Merging Molly features into Signal-JW is an option too, but I guess @johanw666 don't want to increase the maintenance work :)

**Comment by johanw666** [comment]
Merging my features into Molly is much less work (for me at least) than merging Molly's features into mine, for the same result. Further I don't want to use Molly as my main messenger before the no notifications while locked issue is fixed, but that is an entirely different solution.

**Comment by natur960** [comment]
I would like to see a FOSS fork of the things that you both agree about. 

is there such a version ? :)

thanks so much :) .

**Comment by johanw666** [comment]
No, currently there is no such version. And I'm not really interested in putting a lot of work to create a foss version that I myself won't use anyway.

**Comment by natur960** [comment]
@valldrac  - is there such a version on your behalf ?

**Comment by valldrac** [comment]
> I would like to see a FOSS fork of the things that you both agree about. preferably an apk . :)

Molly already has a FOSS version.

> I have added an option to encrypt the plaintext backup and the full backup with the same key as the normal backup

@johanw666 Hmm, writing secrets to disk in plain text is insecure. I know it overwrites the files later, but it doesn't completely fix possible leaks. 

Wouldn't it be easier to maintain a single backup system? And develop instead a packer/unpacker for the Signal format?

**Comment by johanw666** [comment]
Yes, I tried using a secure overwrite (as far as that is possible on flash memory) but that was so slow for the plaintext backup that it was unworkable. I still use that for the small files that contain the database keys for the full backup. Another option would be to rewrite it using streams, like Signal does with video compressing, but that is a major task and only works on Android 8+.

However, I use this code for a few things: the plaintext backup is usefull if I want to add messages to an existing database and not want to completely replace it. I used it once to merge a conversation I had on 2 devices for archiving. The full backup contains more than the standard backup, including expiring messages (OK, I could make an option to backup those too in the standard backup, Signal already did once by mistake) and things like Google tokens. I still have a plan to be able to restore that too when installing Signal for the first time.

**Comment by natur960** [comment]
Hi @johanw666 can u make a version that don't communicate with google servers at all?

**Comment by johanw666** [comment]
> 
> 
> Hi @johanw666 can u make a version that don't communicate with google servers at all?

Probably, but I have no plans on using such a version and no time to maintain it.

**Comment by johanw666** [comment]
Signal never used the Android system sms database.

**Comment by ilikenwf** [comment]
I'm not honestly that worried about it anymore, short of 1-2 people everyone I know finally converted to signal.
